version: '3.7'

services:
  app:
    build: ./
    volumes:
      - ./:/var/www/api-email
    ports:
      - 3002:${PORT}
    environment:
      - NODE_ENV
      - HOST
      - PORT
      - SENDGRID_API_KEY
    command: sh -c 'npm i && npm run dev'
